// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurrantProject.Context;

#nullable disable

namespace RestaurrantProject.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251015120152_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurrantProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Sandwiches"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Meals"
                        });
                });

            modelBuilder.Entity("RestaurrantProject.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyOrderCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Classic pizza with tomato sauce and mozzarella",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Margherita Pizza",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Pepperoni slices over cheesy crust",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Pepperoni Pizza",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Grilled chicken with BBQ sauce",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "BBQ Chicken Pizza",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Blend of mozzarella, cheddar, parmesan, and blue cheese",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Four Cheese Pizza",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Loaded with fresh vegetables",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Veggie Pizza",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Juicy beef patty with cheese and lettuce",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Beef Burger",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Crispy chicken fillet with mayo",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chicken Burger",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Triple-decker sandwich with turkey and egg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Club Sandwich",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Tuna salad with lettuce and tomato",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Tuna Sandwich",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Traditional Egyptian falafel with tahini",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Falafel Sandwich",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Half grilled chicken with rice and salad",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grilled Chicken Meal",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Tender beef steak with mashed potatoes",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Beef Steak Meal",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Grilled kofta with rice and salad",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Kofta Meal",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Crispy fried chicken pieces with fries",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fried Chicken Meal",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyOrderCount = 0,
                            Description = "Breaded fish fillet with tartar sauce",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fish Fillet Meal",
                            Price = 160.00m
                        });
                });

            modelBuilder.Entity("RestaurrantProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurrantProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quanitity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurrantProject.Models.Item", b =>
                {
                    b.HasOne("RestaurrantProject.Models.Category", "category")
                        .WithMany("items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("RestaurrantProject.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurrantProject.Models.Item", "item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurrantProject.Models.Order", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");

                    b.Navigation("order");
                });

            modelBuilder.Entity("RestaurrantProject.Models.Category", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("RestaurrantProject.Models.Order", b =>
                {
                    b.Navigation("orderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
